### ISSUE TITLE
Halo 3 crashes when trying to set up loltracer as the renderer

### ISSUE THREAD

**Issue by Lartu** [iglosiggio/loltracer#1]
Hi there, I've been trying to run Halo 3 using loltracer as the renderer instead of DirectX but it crashes everytime. I get the following error log:

```
error[E0308]: mismatched types
  --> src/lib.rs:54:22
   |
54 |             _ => Err("Re:Re:Felicitaciones Doctor Pombo"),
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected charly `std::io::Error`, found reference
   |
   = note: expected type `std::io::Error`
              found type `&'static pomb`

error: aborting due to previous error

For more information about this error, try `dctodos --explain o2opt`.
```

How can I fix this? Please hurry up because I have to go to a christmas party and I want to finish this game before going. Thank you.

**Comment by iglosiggio** [comment]
Hi, sorry for the inconveniences caused.

Loltracer is a fixed-pipeline renderer and as such it can't be used as a backend for DirectX videogames. If you are interested in using software rendering for playing commercial videogames i would suggest using the wrapper provided by wine with a mesa software renderer.

The current mesa software renderers are:
* swrast (legacy)
* softpipe (reference driver)
* [llvmpipe](https://www.mesa3d.org/llvmpipe.html)
* [openswr](https://www.openswr.org/)

Both llvmpipe and openswr are based on the [gallium architecture](https://gallium.readthedocs.io/en/latest/) and are therefore capable of using the native [DirectX 9 state-tracker](https://wiki.ixit.cz/d3d9).

If you are using windows there are some [builds of mesa](https://fdossena.com/?p=mesa/index.frag) (for a software renderer) and of [wined3d](https://fdossena.com/?p=wined3d/index.frag) (for a directx-to-opengl layer) available.



I'm closing this issue because is unrelated to the purpose of the loltracer project.
